<body>
  <section id="home" class="hero-heading-center">
    <div class="navbar-no-shadow">
      <div data-animation="default" data-collapse="medium" data-duration="400" data-easing="ease" data-easing2="ease" role="banner" class="navbar-no-shadow-container w-nav">
        <div class="container-regular">
          <div class="navbar-wrapper">
            <a href="#" class="navbar-brand w-nav-brand"><img src="images/ww.png" loading="lazy" width="73" sizes="73px" alt="" srcset="images/ww-p-500.png 500w, images/ww-p-800.png 800w, images/ww-p-1080.png 1080w, images/ww.png 1313w"></a>
            <nav role="navigation" class="nav-menu-wrapper w-nav-menu">
              <ul role="list" class="nav-menu w-list-unstyled">
                <li>
                  <a href="https://www.iunderstanditnow.club/#home" class="nav-link">HOME</a>
                </li>
                <li>
                  <a href="https://www.iunderstanditnow.club/#about" class="nav-link">ABOUT</a>
                </li>
                <li class="mobile-margin-top-10">
                  <div class="nav-button-wrapper">
                    <a href="http://t.me/understandonsol" target="_blank" class="w-inline-block"><img src="images/tg.png" loading="lazy" width="50" sizes="(max-width: 767px) 100vw, 50px" alt="" srcset="images/tg-p-500.png 500w, images/tg-p-800.png 800w, images/tg-p-1080.png 1080w, images/tg.png 1500w"></a>
                    <a href="https://x.com/UNDERSTANDCTO" target="_blank" class="w-inline-block"><img src="images/xx.png" loading="lazy" width="50" sizes="(max-width: 767px) 100vw, 50px" alt="" srcset="images/xx-p-500.png 500w, images/xx-p-800.png 800w, images/xx-p-1080.png 1080w, images/xx.png 1563w"></a>
                    <a href="mailto:cryptoprofesor27@gmail.com?subject=I%20UNDERSTAND%20IT%20NOW" class="w-inline-block"><img src="images/gmail.png" loading="lazy" width="50" sizes="(max-width: 767px) 100vw, 50px" alt="" srcset="images/gmail-p-500.png 500w, images/gmail-p-800.png 800w, images/gmail-p-1080.png 1080w, images/gmail.png 1500w"></a>
                  </div>
                </li>
              </ul>
            </nav>
            <div class="menu-button w-nav-button">
              <div class="icon w-icon-nav-menu"></div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="container">
      <div data-w-id="fff061dc-0ecb-c206-f6cb-6878a5f064af" style="opacity:0" class="hero-wrapper">
        <div class="hero-split">
          <a fs-copyclip-message="COPIED" fs-copyclip-element="click" fs-copyclip-text="C1ia2bYoa2V9sSGy9S5139nztQy6Uzz4gzYwuCkRpump" href="#" class="button-primary w-button">CONTRACT</a>
        </div>
      </div>
    </div>
    <div data-w-id="d325da43-23c9-82d2-99ec-8a612b56dc28" style="opacity:0" class="w-layout-blockcontainer container-2 w-container">
      <a href="http://t.me/understandonsol" target="_blank" class="w-inline-block"><img src="images/tg.png" loading="lazy" width="93" sizes="(max-width: 479px) 22vw, 93px" alt="" srcset="images/tg-p-500.png 500w, images/tg-p-800.png 800w, images/tg-p-1080.png 1080w, images/tg.png 1500w"></a>
      <a href="https://x.com/UNDERSTANDCTO" target="_blank" class="w-inline-block"><img src="images/xx.png" loading="lazy" width="93" sizes="(max-width: 479px) 22vw, 93px" alt="" srcset="images/xx-p-500.png 500w, images/xx-p-800.png 800w, images/xx-p-1080.png 1080w, images/xx.png 1563w"></a>
      <a href="https://www.dextools.io/app/en/solana/pair-explorer/AcSs5sGx63u7P4L4Kw11cMFWDnxRHShyVMTriTmkRW7z?t=1731605943119" target="_blank" class="w-inline-block"><img src="images/dexs.png" loading="lazy" width="93" sizes="(max-width: 479px) 22vw, 93px" alt="" srcset="images/dexs-p-500.png 500w, images/dexs-p-800.png 800w, images/dexs-p-1080.png 1080w, images/dexs.png 1375w"></a>
      <a href="https://dexscreener.com/solana/acss5sgx63u7p4l4kw11cmfwdnxrhshyvmtritmkrw7z" target="_blank" class="w-inline-block"><img src="images/desxtr.png" loading="lazy" width="93" sizes="(max-width: 479px) 22vw, 93px" alt="" srcset="images/desxtr-p-500.png 500w, images/desxtr-p-800.png 800w, images/desxtr-p-1080.png 1080w, images/desxtr.png 1500w"></a>
    </div>
  </section>
  <section class="hero-without-image">
    <div class="container">
      <div class="hero-wrapper-two">
        <h1 data-w-id="09dd2668-572b-5c02-75f4-ea79263d5b9d" style="opacity:0" class="heading">ABOUT</h1>
        <p id="about" data-w-id="09dd2668-572b-5c02-75f4-ea79263d5b9f" style="opacity:0" class="margin-bottom-24px">The ‚ÄúI understand it now‚Äù meme is one of the biggest trends rn on TikTok mostly following Trump‚Äôs comeback election victory. When I type the letter ‚ÄúI‚Äù in TikTok it‚Äôs the first thing that comes up.</p>
      </div>
    </div>
  </section>
  <section class="section">
    <div class="w-layout-blockcontainer w-container">
      <div class="w-embed w-script">
        <blockquote class="tiktok-embed" cite="https://www.tiktok.com/@lethalshooter/video/7377510783984471338" data-video-id="7377510783984471338" style="max-width: 605px;min-width: 325px;">
          <section>
            <a target="_blank" title="@lethalshooter" href="https://www.tiktok.com/@lethalshooter?refer=embed">@lethalshooter</a> Double rim was to easy!! I added the POINT GUARD!!‚öîÔ∏èü§Ø -Stay locked in! - <a title="nba" target="_blank" href="https://www.tiktok.com/tag/nba?refer=embed">#NBA</a>
            <a title="viral" target="_blank" href="https://www.tiktok.com/tag/viral?refer=embed">#Viral</a>
            <a title="basketball" target="_blank" href="https://www.tiktok.com/tag/basketball?refer=embed">#Basketball</a>
            <a title="nba" target="_blank" href="https://www.tiktok.com/tag/nba?refer=embed">#NBA</a>
            <a title="redbull" target="_blank" href="https://www.tiktok.com/tag/redbull?refer=embed">#RedBull</a>
            <a title="lethalshooter" target="_blank" href="https://www.tiktok.com/tag/lethalshooter?refer=embed">#LethalShooter</a>
            <a target="_blank" title="‚ô¨ original sound - Lethal Shooter" href="https://www.tiktok.com/music/original-sound-7377510814787455787?refer=embed">‚ô¨ original sound - Lethal Shooter</a>
          </section>
        </blockquote>
        <script async="" src="https://www.tiktok.com/embed.js"></script>
      </div>
    </div>
    <div class="w-layout-blockcontainer w-container">
      <div class="w-embed w-script">
        <blockquote class="tiktok-embed" cite="https://www.tiktok.com/@lethalshooter/video/7434679968229149998" data-video-id="7434679968229149998" style="max-width: 605px;min-width: 325px;">
          <section>
            <a target="_blank" title="@lethalshooter" href="https://www.tiktok.com/@lethalshooter?refer=embed">@lethalshooter</a> I understand it now!üéØ <a title="lethalshooter" target="_blank" href="https://www.tiktok.com/tag/lethalshooter?refer=embed">#LethalShooter</a>
            <a title="iunderstanditnow" target="_blank" href="https://www.tiktok.com/tag/iunderstanditnow?refer=embed">#iunderstanditnow</a>
            <a title="viral" target="_blank" href="https://www.tiktok.com/tag/viral?refer=embed">#VIRAL</a>
            <a target="_blank" title="‚ô¨ original sound - Lethal Shooter" href="https://www.tiktok.com/music/original-sound-7434679945538472747?refer=embed">‚ô¨ original sound - Lethal Shooter</a>
          </section>
        </blockquote>
        <script async="" src="https://www.tiktok.com/embed.js"></script>
      </div>
    </div>
    <div class="w-layout-blockcontainer w-container">
      <div class="w-embed w-script">
        <blockquote class="tiktok-embed" cite="https://www.tiktok.com/@lethalshooter/video/7432411556408724778" data-video-id="7432411556408724778" style="max-width: 605px;min-width: 325px;">
          <section>
            <a target="_blank" title="@lethalshooter" href="https://www.tiktok.com/@lethalshooter?refer=embed">@lethalshooter</a> Making gummy bears in a water bottle. Y‚Äôall better stop playing with me online. I watch ALL your post making fun of me!üòÇüòÇüòÇ <a title="lethalshooter" target="_blank" href="https://www.tiktok.com/tag/lethalshooter?refer=embed">#LethalShooter</a>
            <a title="viral" target="_blank" href="https://www.tiktok.com/tag/viral?refer=embed">#VIRAL</a>
            <a target="_blank" title="‚ô¨ original sound - Lethal Shooter" href="https://www.tiktok.com/music/original-sound-7432411561567734571?refer=embed">‚ô¨ original sound - Lethal Shooter</a>
          </section>
        </blockquote>
        <script async="" src="https://www.tiktok.com/embed.js"></script>
      </div>
    </div>
    <div class="w-layout-blockcontainer w-container">
      <div class="w-embed w-script">
        <blockquote class="tiktok-embed" cite="https://www.tiktok.com/@lethalshooter/video/7435681529247976746" data-video-id="7435681529247976746" style="max-width: 605px;min-width: 325px;">
          <section>
            <a target="_blank" title="@lethalshooter" href="https://www.tiktok.com/@lethalshooter?refer=embed">@lethalshooter</a> Y‚Äôall better stop playing with me in the comments‚Ä¶ I understand it now!üéØ <a title="lethalshooter" target="_blank" href="https://www.tiktok.com/tag/lethalshooter?refer=embed">#LethalShooter</a>
            <a title="viral" target="_blank" href="https://www.tiktok.com/tag/viral?refer=embed">#VIRAL</a>
            <a title="iunderstanditnow" target="_blank" href="https://www.tiktok.com/tag/iunderstanditnow?refer=embed">#iunderstanditnow</a>
            <a title="insane" target="_blank" href="https://www.tiktok.com/tag/insane?refer=embed">#INSANE</a>
            <a title="ballislife" target="_blank" href="https://www.tiktok.com/tag/ballislife?refer=embed">#Ballislife</a>
            <a target="_blank" title="‚ô¨ original sound - Lethal Shooter" href="https://www.tiktok.com/music/original-sound-7435681512843987754?refer=embed">‚ô¨ original sound - Lethal Shooter</a>
          </section>
        </blockquote>
        <script async="" src="https://www.tiktok.com/embed.js"></script>
      </div>
    </div>
  </section>
  <section class="gallery-scroll">
    <div class="container-3">
      <div class="gallery-wrapper-2">
        <div id="w-node-d84c3cd5-e3f8-d151-6b3f-4d1d1c45cc5e-001603c6" class="gallery-grid-2">
          <div id="virtual-booths" class="gallery-image-wrapper w-node-d84c3cd5-e3f8-d151-6b3f-4d1d1c45cc5f-001603c6"><img class="gallery-image-2 shadow-two" src="images/trump2.png" alt="" style="opacity:0" sizes="94vw" data-w-id="d84c3cd5-e3f8-d151-6b3f-4d1d1c45cc60" id="w-node-d84c3cd5-e3f8-d151-6b3f-4d1d1c45cc60-001603c6" loading="lazy" srcset="images/trump2-p-500.png 500w, images/trump2-p-800.png 800w, images/trump2-p-1080.png 1080w, images/trump2.png 1500w"></div>
          <div id="access-dash" class="gallery-image-wrapper w-node-d84c3cd5-e3f8-d151-6b3f-4d1d1c45cc63-001603c6"><img class="gallery-image-2 shadow-two" src="images/trump3.png" alt="" style="opacity:0" sizes="94vw" data-w-id="d84c3cd5-e3f8-d151-6b3f-4d1d1c45cc64" id="w-node-d84c3cd5-e3f8-d151-6b3f-4d1d1c45cc64-001603c6" loading="lazy" srcset="images/trump3-p-500.png 500w, images/trump3-p-800.png 800w, images/trump3-p-1080.png 1080w, images/trump3.png 1563w"></div>
          <div id="lead-retrieval" class="gallery-image-wrapper w-node-d84c3cd5-e3f8-d151-6b3f-4d1d1c45cc67-001603c6"><img class="gallery-image-2 shadow-two" src="images/trump1.png" alt="" style="opacity:0" sizes="94vw" data-w-id="d84c3cd5-e3f8-d151-6b3f-4d1d1c45cc68" id="w-node-d84c3cd5-e3f8-d151-6b3f-4d1d1c45cc68-001603c6" loading="lazy" srcset="images/trump1-p-500.png 500w, images/trump1-p-800.png 800w, images/trump1-p-1080.png 1080w, images/trump1.png 1500w"></div>
          <div id="lead-scoring" class="gallery-image-wrapper w-node-d84c3cd5-e3f8-d151-6b3f-4d1d1c45cc6b-001603c6"><img class="gallery-image-2 shadow-two" src="images/photo_2024-11-15_02-02-24.jpg" alt="" style="opacity:0" sizes="94vw" data-w-id="d84c3cd5-e3f8-d151-6b3f-4d1d1c45cc6c" id="w-node-d84c3cd5-e3f8-d151-6b3f-4d1d1c45cc6c-001603c6" loading="lazy" srcset="images/photo_2024-11-15_02-02-24-p-500.jpg 500w, images/photo_2024-11-15_02-02-24-p-800.jpg 800w, images/photo_2024-11-15_02-02-24.jpg 1091w"></div>
          <div id="sponsored-sections" class="gallery-image-wrapper w-node-d84c3cd5-e3f8-d151-6b3f-4d1d1c45cc6f-001603c6"><img class="gallery-image-2 shadow-two" src="images/photo_2024-11-15_02-02-28.jpg" alt="" style="opacity:0" sizes="94vw" data-w-id="d84c3cd5-e3f8-d151-6b3f-4d1d1c45cc70" id="w-node-d84c3cd5-e3f8-d151-6b3f-4d1d1c45cc70-001603c6" loading="lazy" srcset="images/photo_2024-11-15_02-02-28-p-500.jpg 500w, images/photo_2024-11-15_02-02-28-p-800.jpg 800w, images/photo_2024-11-15_02-02-28-p-1080.jpg 1080w, images/photo_2024-11-15_02-02-28.jpg 1280w"></div>
        </div>
      </div>
    </div>
  </section>
  <script src="https://d3e54v103j8qbb.cloudfront.net/js/jquery-3.5.1.min.dc5e7f18c8.js?site=67367c462b00a252001603a5" type="text/javascript" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
  <script src="js/webflow.js" type="text/javascript"></script>
</body>
